### PR TITLE
Restore diff

### PR DESCRIPTION
**Pull request by kluete**
restored examples/diff

### CODE REVIEW

**Comment by AndreyG** [comment]
Thank you for contribution! I agree with almost all at bottom of fact, but I have some stylistic comments listed above.

**Comment by kluete** [comment]
cool.

Btw I found it hard to unequivocally conclude which examples or functions potentially modify a git repo, vs strict read-only. I know it's hard to propagate constness across c++/ansi-c boundaries but it'd be nice.

Cheers!

-- p

**Comment by AndreyG** [comment]
Could you fix this pull request or prepare new one respecting latest 'master' branch changes and my comments to this one?
If you have any questions or ideas, I will be glad to answer.

**Comment by kluete** [comment]
sure I'll try but I'm preparing for a 3-month stint in Los Angeles so don't have as much spare time.

cheers,

-- p

**Pull request closed without merging**
